export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const ADD_MESSAGE = 'ADD_MESSAGE'
export const SET_CLEAR_MESSAGES = 'SET_CLEAR_MESSAGES'

export const ADD_TO_CURRENT_USERS_TYPING = 'ADD_TO_CURRENT_USERS_TYPING'
export const REMOVE_FROM_CURRENT_USERS_TYPING =
  'REMOVE_FROM_CURRENT_USERS_TYPING'
export const SET_CLEAR_CURRENT_USERS_TYPING = 'SET_CLEAR_CURRENT_USERS_TYPING'

export const CHANGE_THEME = 'CHANGE_THEME'

export const FORCE_UPDATE = 'FORCE_UPDATE'
